using JamesFrowen;
using JamesFrowen.ScriptableVariables;
using Unity.Profiling;
using UnityEngine;
using UnityEngine.Rendering;

namespace NuclearOption.Effects
{
	public class TreeRenderer : MonoBehaviour
	{
		private static readonly ProfilerMarker ComputeMarker = new ProfilerMarker("TreeRenderer.Compute");

		private static readonly ProfilerMarker RenderMarker = new ProfilerMarker("TreeRenderer.Render");

		[Tooltip("Controlled by game settings")]
		[ReadOnly]
		public float TreeRangeMultiplier = 1f;

		[Header("Tree Settings")]
		[Label("Position data generated by TerrainScatter", true)]
		public TextAsset PositionData;

		[SerializeField]
		private Mesh mesh;

		[SerializeField]
		private Material material;

		[SerializeField]
		private float viewRadius;

		[SerializeField]
		private float meshRadius = 10f;

		[Header("Blast Settings")]
		[SerializeField]
		private float clearTreeRadiusMultiplier = 0.5f;

		[Header("Color Settings")]
		public Texture2D LushMap;

		public MinMax AltitudeRange;

		public float AltIntensity;

		public float LushIntensity;

		public float LargeNoiseScale;

		public float NoiseSmallScale;

		public float BlastIntensity;

		[Header("Render Settings")]
		[Tooltip("0.5 means we allocate for 50% of the possible grass blades. Lower = less VRAM, higher = less chance of holes.")]
		[Range(0f, 1f)]
		public float VisibleBufferSizePercent = 0.1f;

		[SerializeField]
		private ComputeShader treeColorCompute;

		[SerializeField]
		private ComputeShader clearShader;

		private GraphicsBuffer treePositionBuffer;

		private GraphicsBuffer visiblePositionBuffer;

		private GraphicsBuffer treeColorBuffer;

		private MaterialPropertyBlock treeMaterialProps;

		private RenderParams renderParams;

		public uint ArgIndex { get; set; }

		private void OnDestroy()
		{
			treePositionBuffer?.Release();
			visiblePositionBuffer?.Release();
			treeColorBuffer?.Release();
		}

		public void CommandSetup(DetailRenderer.RendererOffsets argHelper)
		{
			int num = ScatterLoad.LoadPositionCount(PositionData);
			int num2 = Mathf.Max(1024, num);
			int count = Mathf.Max(1024, Mathf.CeilToInt((float)num2 * VisibleBufferSizePercent));
			treePositionBuffer = new GraphicsBuffer(GraphicsBuffer.Target.Structured | GraphicsBuffer.Target.Append, num2, 12);
			treePositionBuffer.name = "TreePositionBuffer";
			ScatterLoad.Load(PositionData, num, treePositionBuffer);
			visiblePositionBuffer = new GraphicsBuffer(GraphicsBuffer.Target.Structured | GraphicsBuffer.Target.Append, count, 12);
			visiblePositionBuffer.name = "treeVisiblePositionBuffer";
			treeColorBuffer = new GraphicsBuffer(GraphicsBuffer.Target.Structured, count, 8);
			treeColorBuffer.name = "TreeColorBuffer";
			argHelper.Set(argHelper.GroupCount_1().Stride, new GroupCount
			{
				groupX = (uint)(num + 63) / 64u,
				groupY = 1u,
				groupZ = 1u,
				total = (uint)num
			});
			argHelper.Set(argHelper.GroupCount_2().Stride, default(GroupCount));
			argHelper.Set(argHelper.DrawArgs().Stride, new GraphicsBuffer.IndirectDrawIndexedArgs
			{
				indexCountPerInstance = mesh.GetIndexCount(0),
				instanceCount = 0u,
				baseVertexIndex = mesh.GetBaseVertex(0),
				startIndex = mesh.GetIndexStart(0),
				startInstance = 0u
			});
			treeMaterialProps = new MaterialPropertyBlock();
			treeMaterialProps.SetBuffer(ShaderIds.ID_PositionBuffer, visiblePositionBuffer);
			treeMaterialProps.SetBuffer(ShaderIds.ID_ColorDataBuffer, treeColorBuffer);
			Bounds worldBounds = new Bounds(Vector3.zero, 16384f * Vector3.one);
			renderParams = new RenderParams(material)
			{
				matProps = treeMaterialProps,
				worldBounds = worldBounds,
				shadowCastingMode = ShadowCastingMode.On,
				receiveShadows = true
			};
		}

		public void ClearTrees(CommandBuffer cmd, DetailRenderer.RendererOffsets argHelper, BlastManager.DetailBlast blast)
		{
			blast.Radius *= clearTreeRadiusMultiplier;
			ColorLog<BlastManager>.Info($"Clearing trees at {blast}");
			cmd.BeginSample("TreeRenderer.ClearTrees");
			int kernelIndex = clearShader.FindKernel(ShaderIds.Kernel_Main);
			cmd.SetComputeBufferParam(clearShader, kernelIndex, ShaderIds.ID_PositionBuffer, treePositionBuffer);
			cmd.SetCountBuffer(clearShader, kernelIndex, argHelper.GroupCount_1());
			cmd.SetComputeVectorParam(clearShader, ShaderIds.ID_DetailBlast, blast.ToVector4());
			cmd.DispatchCompute(clearShader, kernelIndex, argHelper.Buffer, argHelper.GroupCount_1().Byte);
			cmd.EndSample("TreeRenderer.ClearTrees");
		}

		public void UpdatePositions(CommandBuffer cmd, DetailRenderer.RendererOffsets argHelper)
		{
			using (ComputeMarker.Auto())
			{
				cmd.BeginSample("TreeRenderer");
				ComputeFrustumCulling.RunCull(cmd, ComputeFrustumCulling.RunFlags.UseGlobal, argHelper.GroupCount_1(), treePositionBuffer, visiblePositionBuffer, meshRadius, viewRadius * TreeRangeMultiplier);
				cmd.CopyCounterValue(visiblePositionBuffer, argHelper.Buffer, argHelper.GroupCount_2().Total().Byte);
				cmd.CopyCounterValue(visiblePositionBuffer, argHelper.Buffer, argHelper.DrawArgs().InstanceCount().Byte);
				ComputeGroupCount.Run(cmd, argHelper.GroupCount_2());
				cmd.BeginSample("TreeRenderer.Color");
				int kernelIndex = treeColorCompute.FindKernel("CSMain");
				cmd.SetComputeBufferParam(treeColorCompute, kernelIndex, ShaderIds.ID_VisibleBuffer, visiblePositionBuffer);
				cmd.SetComputeBufferParam(treeColorCompute, kernelIndex, ShaderIds.ID_ColorDataBuffer, treeColorBuffer);
				cmd.SetCountBuffer(treeColorCompute, kernelIndex, argHelper.GroupCount_2());
				cmd.SetComputeTextureParam(treeColorCompute, kernelIndex, ShaderIds.ID_LushMap, LushMap);
				cmd.SetComputeVectorParam(treeColorCompute, ShaderIds.ID_AltitudeRange, AltitudeRange.ToVector4());
				cmd.SetComputeFloatParam(treeColorCompute, ShaderIds.ID_AltIntensity, AltIntensity);
				cmd.SetComputeFloatParam(treeColorCompute, ShaderIds.ID_LushIntensity, LushIntensity);
				cmd.SetComputeFloatParam(treeColorCompute, ShaderIds.ID_LargeNoiseScale, LargeNoiseScale);
				cmd.SetComputeFloatParam(treeColorCompute, ShaderIds.ID_NoiseSmallScale, NoiseSmallScale);
				cmd.SetComputeFloatParam(treeColorCompute, ShaderIds.ID_BlastIntensity, BlastIntensity);
				cmd.DispatchCompute(treeColorCompute, kernelIndex, argHelper.Buffer, argHelper.GroupCount_2().Byte);
				cmd.EndSample("TreeRenderer.Color");
				cmd.EndSample("TreeRenderer");
			}
		}

		public void Render(DetailRenderer.RendererOffsets argHelper)
		{
			using (RenderMarker.Auto())
			{
				Graphics.RenderMeshIndirect(in renderParams, mesh, argHelper.Buffer, 1, (int)argHelper.DrawArgs().Stride);
			}
		}
	}
}
